# Generated by Django 5.2.7 on 2025-10-25 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(default='237XXXXXXXXX', help_text='Format: 237XXXXXXXXX (sans le +)', max_length=20, verbose_name='Numéro WhatsApp')),
                ('contact_email', models.EmailField(default='contact@niasotac.com', max_length=254, verbose_name='Email de contact')),
                ('contact_phone', models.CharField(default='+229 00 00 00 00', max_length=20, verbose_name='Téléphone de contact')),
                ('contact_address', models.CharField(default='Cotonou, Bénin', max_length=200, verbose_name='Adresse')),
                ('company_name', models.CharField(default='NIASOTAC TECHNOLOGIE', max_length=100, verbose_name="Nom de l'entreprise")),
                ('company_description', models.TextField(default='Votre revendeur tech de confiance au Bénin. Produits de qualité à prix compétitifs.', verbose_name="Description de l'entreprise")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
    ]
